# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
    body_converter:
        enabled: true
    zone:
        - { path: ^/api }
    serializer:
        serialize_null:  false
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true

    format_listener:
        enabled: true
        rules:
            -
                path: ^/api/*
                prefer_extension: false
                priorities:
                    - json

    versioning:
        enabled: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'